### ISSUE TITLE
Get-EntraUserManager ignores Property parameter

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/entra-powershell#1090]
Checking some part of the script. If `Property` parameter is specified then `$URI` should contain $select with properties, but `$URI` is overridden by

    $URI = "https://graph.microsoft.com/v1.0/users/$($params.UserId)/manager?`$select=*"

https://github.com/microsoftgraph/entra-powershell/blob/main/module/Entra/customizations/Get-EntraUserManager.ps1#L19-L31

**Comment by snehalkotwal** [comment]
@MartinM85  Thank you for raising the bug, We are looking into it.

**Comment by SteveMutungi254** [comment]
@MartinM85 : Could you confirm if the fixes are Ok as the original poster?

**Comment by MartinM85** [comment]
@SteveMutungi254 The fix looks good.
