### ISSUE TITLE
Application Proxy cmdlets do not exist in Microsoft.Graph.Entra PowerShell module 

### ISSUE THREAD

**Issue by lucafabbri365** [microsoftgraph/entra-powershell#1104]
**Describe the bug**
The **Microsoft.Graph.Entra** PowerShell module doesn't include **Application Proxy** cmdlets listed in this [article](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.entra/?view=entra-powershell#application-proxy).

**To Reproduce**
1. Execute `Install-Module -Name Microsoft.Graph.Entra -Repository PSGallery -AllowPrerelease`
2. Execute `Get-Command Get-EntraApplicationProxyApplication`
**Get-Command: The term 'Get-EntraApplicationProxyApplication' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.**

**Expected behavior**
I expect the Application Proxy cmdlets to work, as they are documented in the article.

**Module Version**
`0.16.0`

**Environment Data**
```
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**
I have noticed, however, that these cmdlets are included in the beta module Microsoft.Graph.Entra.Beta (`Get-EntraBetaApplicationProxyApplication`). Why are they documented in Microsoft.Graph.Entra documentation if they do not exist ?

Thank you

**Comment by v-varshamane** [comment]
@lucafabbri365 : Thanks for raising this issue.
Proxy Entra cmdlets development not yet done as we don't have V1.0 graph api's available at the moment.
So, we have moved these documents in future reference folder for now.
Once cmdlets development will be completed, we will add those docs back to respective folders of docs.
