### ISSUE TITLE
Find-EntraPermission needs to have 2 parameter sets as Find-MgGraphPermission

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/entra-powershell#1118]
`Find-MgGraphPermission` has two parameter sets. `-All` and `-SearchString` are in separated sets.

`Find-EntraPermission` has only one parameter set. A user can tab-complete -SearchString and -All, try to use them both, and command will fail at the runtime.

```powershell
PS> Find-EntraPermission -SearchString "user.read" -All
Find-MgGraphPermission: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

**Comment by emmanuel-karanja** [comment]
@alexandair please confirm this is resolved via this PR https://github.com/microsoftgraph/entra-powershell/pull/1145
