### ISSUE TITLE
Get-EntraServicePrincipal - AppRoleAssignment and AppRoleAssignedTo returns wrong data.

### ISSUE THREAD

**Issue by alflokken** [microsoftgraph/entra-powershell#1161]
"TargetName" for [Get-EntraServicePrincipalAppRoleAssignment](https://github.com/microsoftgraph/entra-powershell/blob/main/module/Entra/customizations/Get-EntraServicePrincipalAppRoleAssignment.ps1) and [Get-EntraServicePrincipalAppRoleAssignedTo](https://github.com/microsoftgraph/entra-powershell/blob/main/module/Entra/customizations/Get-EntraServicePrincipalAppRoleAssignedTo.ps1) have been switched around?

![image](https://github.com/user-attachments/assets/8f7a30e1-8136-4891-a5dc-dee0aa58e3ea)

**Comment by SteveMutungi254** [comment]
Thanks, @alflokken, for your contributions! The changes are approved.
