### ISSUE TITLE
Duplicated examples in the Get-EntraUserOAuth2PermissionGrant help

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/entra-powershell#1163]
In the help for the `Get-EntraUserOAuth2PermissionGrant` command, examples 1 and 2 are the same.
Also, there is a bunch of typos and references to ObjectId when UserId is used.

**Comment by SteveMutungi254** [comment]
Thanks, @alexandair, for bringing this up! We're looking into it and will tag you once the fix is complete. We will include a fix in the upcoming release.
