### ISSUE TITLE
Continued use of "AzureAD" mixed with "Entra" is confusing

### ISSUE THREAD

**Issue by SamErde** [microsoftgraph/entra-powershell#367]
The continued use of "AzureAD" in documentation, comments, and function names is confusing.  

Is some of this code a fork from the AzureAD module?  
Is there a plan to replace all instances of the string "AzureAD" with "Entra" or "EntraID" in this repo? I would humbly suggest that change be completed before leaving private preview.

**Comment by SteveMutungi254** [comment]
Work completed.
