### ISSUE TITLE
Use own Enterprise Application for Entra PowerShell

### ISSUE THREAD

**Issue by Weishaupt** [microsoftgraph/entra-powershell#375]
I really do like the approach of simplifying the usage of Entra PowerShell Module in comparison to PowerShell Graph.

I still do find the authentication of Entra PowerShell a bit cumbersome. From the previous `AzureAD` variant, admins are used to perform all required actions without further checking the required permissions. (Do I just want to read, or do I also need write access?) I'd propose a similar solution for Entra PowerShell. Instead of relying on the default enterprise application that the PowerShell Graph uses in the background (ID `14d82eec-204b-4c2f-b7e8-296a70dab67e`) I'd suggest a seperate Entra ID PowerShell Enterprise Application with all the required Permissions in the delegated scope.

On the first usage, the user would call `Connect-EntraID` and then start the usual enterprise app consent flow. On subsequent connections the user would sign in without any additional permission promts. Before each command, Entra PowerShell could check, if the current context allows for the operation and automatically aquire additional required permissios with the usual delegated permission flow.

I think this approach reduces overhead for IT-Pros and most closely micics current default behaviour.

**Comment by SteveMutungi254** [comment]
An article on this issue created in our official public documentation - https://learn.microsoft.com/powershell/entra-powershell/entra-powershell-best-practices
