### ISSUE TITLE
Windows 11 profile folder creation on cloud only user give problems with special characters from Entra ID displayname

### ISSUE THREAD

**Issue by aavdberg** [microsoftgraph/entra-powershell#376]
When I have a user from Entra ID with special characters in de displayname this will give problems in Windows when the profile folder is created

for example my name in  Entra ID displayname is written as André van den Berg and then a profile folder with the name AndrévandenBerg is created.

This will give many problems with software that can't handle the special characters.

Example where i have this problem is Windows app for Cloud PC.

Already created in CCP in the Cloud PC channel already a post about this.

![image](https://github.com/microsoftgraph/entra-powershell/assets/22030609/1710bb29-d87b-47a5-bb75-b7f09c969451)

**Comment by SteveMutungi254** [comment]
Requires an external team to fix.
