### ISSUE TITLE
[0.8] It's expected that Entra commands return real Microsoft Graph types and not PSCustomObjects

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/entra-powershell#831]
Get-EntraGroup, Get-EntraApplication, Get-EntraServicePrincipal return real Microsoft Graph object types (e.g. Microsoft.Graph.PowerShell.Models.MicrosoftGraphGroup).

Get-EntraUser and other user-related cmdlets return PSCustomObjects.
Shouldn't they be casted to the Microsoft Graph types?

**Comment by alexandair** [comment]
@KenitoInc @SteveMutungi254 
Why is this issue closed?
Get-EntraUserManager and Get-EntraUSerDirectReport still return PSCustomObject type.

It would be nice if the OP is informed when issue is closed. This issue is closed without any comments.

**Comment by SteveMutungi254** [comment]
@alexandair : Going forward, we will be tagging the OP and enrich completion notes.

**Comment by alexandair** [comment]
Please, also reopen the issue.

**Comment by SteveMutungi254** [comment]
Reopening the issue.

**Comment by SteveMutungi254** [comment]
@alexandair : The issue was resolved via this PR - https://github.com/microsoftgraph/entra-powershell/pull/965 

We will be merging changes on 08.08. Confirm if the changes are good.

cc: @v-varshamane, @KenitoInc
