### ISSUE TITLE
Installation instructions need to be updated

### ISSUE THREAD

**Issue by adamedx** [microsoftgraph/entra-powershell#844]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of `Microsoft.Graph.Entra` or `Microsoft.Graph.Entra.Beta`.
- Please search the existing issues to see if there has been a similar issue filed.

**Describe the bug**
The README itself should have the instructions to install from PowerShell gallery, i.e. `install-module microsoft.graph.entra`

**To Reproduce**
Visit https://github.com/microsoftgraph/entra-powershell -- there are no instructions for installation, though there is a link to some complicated instructions that are only needed for installation of privately built versions.

**Expected behavior**
It should look like other powershell repositories, see MS Graph PowerShell SDK: https://github.com/microsoftgraph/msgraph-sdk-powershell?tab=readme-ov-file#getting-started

**Comment by SteveMutungi254** [comment]
I have updated the documentation, including README.md

**Comment by SteveMutungi254** [comment]
Work completed.
