### ISSUE TITLE
Microsoft.Graph.Entra fails to load  because the manifest is missing the dependencies

### ISSUE THREAD

**Issue by adamedx** [microsoftgraph/entra-powershell#845]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of `Microsoft.Graph.Entra` or `Microsoft.Graph.Entra.Beta`.
- Please search the existing issues to see if there has been a similar issue filed.

**Describe the bug**
You can't load the microsoft.graph.entra module on a machine unless you've manually installed module dependencies. 

**To Reproduce**
1. Go to a system that does not have any microsoft.graph.* modules installed on it
2. Run `install-module microsoft.graph.entra -allowprerelease`
3. Run `import-module microsoft.graph.entra`

**Expected behavior**
Expect that no errors are shown. You can then run the commands in the module. But here's what you get instead:

```powershell
Import-Module Microsoft.Graph.Entra
Import-Module: The required module 'Microsoft.Graph.Users' is not loaded. Load the module or remove the module from 'RequiredModules' in the file 'C:\Users\adamed\Documents\altmodules\Microsoft.Graph.Entra\0.8.0\Microsoft.Graph.Entra.psd1'.
```

Module version: `0.9.0-preview`

The cause is that the manifest has no dependencies, so `install-module` doesn't install the other modules required for this module to work. Fix should be simple -- add the dependencies to the module manifest and re-publish.

* https://www.powershellgallery.com/packages/Microsoft.Graph.Entra/0.9.0-preview
```
Dependencies
This module has no dependencies.
```

Instead, it should list the dependencies.

**Comment by KenitoInc** [comment]
Resolved by https://github.com/microsoftgraph/entra-powershell/pull/853
