### ISSUE TITLE
No release or version tag for published versions 0.8 and 0.9 of Entra PowerShell

### ISSUE THREAD

**Issue by adamedx** [microsoftgraph/entra-powershell#859]
**Describe the bug**
The latest version of Entra PowerShell at this time is 0.9 and it can be found in PowerShell Gallery here: https://www.powershellgallery.com/packages/Microsoft.Graph.Entra/0.9.0-preview.

However, there is no tag or release for it in this repository the latest tag is 0.7 right now, i.e. this path does not resolve: https://github.com/microsoftgraph/entra-powershell/releases/tag/0.9-preview. 

Expectation is that every release is tagged, especially any release published to PowerShell Gallery. The publishing process and / or build process should tag the repository so that no manual work is required to do this. You can check with the MS Graph SDK team to see how they accomplish this.

**Comment by snehalkotwal** [comment]
@adamedx Thanks for raising the issue, we are looking into it.
