### ISSUE TITLE
Local build does not create artifacts in bin folder

### ISSUE THREAD

**Issue by SamErde** [microsoftgraph/entra-powershell#874]
**Describe the bug**
The instructions to build the module locally do not work for me in PowerShell or Windows PowerShell. Running `.\build\Install-Dependencies.ps1 -ModuleName Entra` installs of the module dependencies and creates the bin folder, but does not build the module files.

**To Reproduce**
1. Clone or download and extract the repo into the folder .\entra-powershell
2. `cd entra-powershell`
3. `.\build\Install-Dependencies.ps1 -ModuleName Entra`
4. `Install-Module -Name PlatyPS`
5. `. .\build\Common-functions.ps1`
6. `Create-ModuleHelp -Module Entra`

At this point, the only file created was Microsoft.Graph.Entra-Help.xml. I then ran .\build\Create-CompatModule.ps1 -Module Entra and got the following output:

```powershealth
.\build\Create-CompatModule.ps1 -Module Entra
Creating custom function map for Set-EntraApplication
PropertyNotFoundException: C:\Users\[...]\Repositories\Public\entra-powershell\src\CompatibilityAdapterBuilder.ps1:683:16
Line |
 683 |              if($attrib.ParameterSetName -ne "__AllParameterSets"){
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'ParameterSetName' cannot be found on this object. Verify that the property exists.
```

**Expected behavior**
Build the module including its manifest and file structure. (Does this depend on a build task being configured in the .vscode folder?)

**Debug Output**
```powershell
❯ .\build\Install-Dependencies.ps1 -ModuleName EntraBeta -Debug
❯ .\build\Install-Dependencies.ps1 -ModuleName EntraBeta -Verbose
VERBOSE: Installing Module AzureADPreview
VERBOSE: Installing Module Microsoft.Graph.Beta.DirectoryObjects
VERBOSE: Installing Module Microsoft.Graph.Beta.Users
VERBOSE: Installing Module Microsoft.Graph.Beta.Users.Actions
VERBOSE: Installing Module Microsoft.Graph.Beta.Users.Functions
VERBOSE: Installing Module Microsoft.Graph.Beta.Groups
VERBOSE: Installing Module Microsoft.Graph.Beta.Identity.DirectoryManagement
VERBOSE: Installing Module Microsoft.Graph.Beta.Identity.Governance
VERBOSE: Installing Module Microsoft.Graph.Beta.Identity.SignIns
VERBOSE: Installing Module Microsoft.Graph.Beta.Applications
VERBOSE: Installing Module Microsoft.Graph.Beta.Reports
```

**Module Version**
```powershell
❯ Get-Module -Name 'Microsoft.Graph.Entra'

Name                  Version PreRelease ExportedCommands
----                  ------- ---------- ----------------
Microsoft.Graph.Entra 0.10.0             {Add-EntraAdministrativeUnitMember, Add-EntraApplicationO…
```

**Environment Data**
```powershell
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Screenshots**
![image](https://github.com/microsoftgraph/entra-powershell/assets/20478745/84e2f804-417c-493a-8437-41645fb6abcf)

**Comment by snehalkotwal** [comment]
@SamErde Thanks for raising the issue, we are looking into it.

**Comment by v-akarke** [comment]
Hi @SamErde, 
The command `.\build\Install-Dependencies.ps1 -ModuleName Entra` installs the necessary dependencies but does not build the module files. 
To build the module files and help files, follow these steps after running `.\build\Install-Dependencies.ps1 -ModuleName Entra` : 
![image](https://github.com/microsoftgraph/entra-powershell/assets/142799789/4ecf7de0-e689-47a4-aa0e-a730b1dcbe3b)

This process will generate the help files and module files. Once you import the module, you will be able to use it. 
For any queries or additional information, please refer to the `BUILD.md` file inside the build folder.

**Comment by SamErde** [comment]
Thanks. I should have been more clear in my description: I was following the instructions on [BUILD.md](https://github.com/microsoftgraph/entra-powershell/blob/main/build/BUILD.md) and still not successful. I'll update the description to note that I ran: 

cd .\Public\entra-powershell
.\build\Install-Dependencies.ps1 -ModuleName Entra
Install-Module -Name PlatyPS
. .\build\Common-functions.ps1
Create-ModuleHelp -Module Entra

**Comment by SamErde** [comment]
The local build script works now. Thank you!

**Comment by SamErde** [comment]
Thanks for the update!
