### ISSUE TITLE
Increase the usability with parameter aliases

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/entra-powershell#879]
AzureAD commands use the `-ObjectId` parameter.
Microsoft Graph PowerShell commands use the specific parameter names like `-UserId`, `-GroupId`...

Add parameter aliases when it's appropriate, so that users can run:
```powershell
Get-EntraUser -ObjectId ...
Get-EntraUser -UserId ...
Get-EntraApplication -ObjectId ...
Get--EntraApplication -ApplicationId ...
```

**Comment by snehalkotwal** [comment]
@alexandair Thanks for raising the issue, We are looking into it.

**Comment by SteveMutungi254** [comment]
@alexandair: We're close to finalizing work on this issue and wanted to give you a heads-up for early feedback. You can expect to see a lot of PRs coming in for this.

**Comment by SteveMutungi254** [comment]
@alexandair: I’d like to close this issue as the [main work](https://github.com/microsoftgraph/entra-powershell/pull/1050) is complete. We’ll raise PRs for any edge cases or missed commands as needed.

**Comment by alexandair** [comment]
Sure, go ahead.
