### ISSUE TITLE
The $keysChanged variable is assigned but never used

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/entra-powershell#880]
Most of the definitions of Entra commands contain a line similar to the following:
```powershell
  $keysChanged = @{RefObjectId = "BodyParameter"; ObjectId = "Id"}
``` 

The `$keysChanged` variable is assigned but never used.
Unless it's planned to use it in future, it should be removed.

**Comment by snehalkotwal** [comment]
@alexandair Thanks for raising the issue, We are looking into it.
