### ISSUE TITLE
-Verbose:$false and -Debug:$false shouldn't output verbose and debug streams

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/entra-powershell#885]
If we use Entra PowerShell commands with `-Verbose:$false` and `-Debug:$false` switches, the output should be the same as when we don't specify these switches. At the moment, `-Verbose:$false` and `-Debug:$false` behave wrongly as `-Verbose` and `-Debug`.

Here is an example with the `Set-EntraUserManager` command:

```powershell
PS> Set-EntraUserManager -ObjectId $AdeleM.Id -RefObjectId $Diego.id -Verbose:$false
VERBOSE: Performing the operation "Set-MgUserManagerByRef_Set" on target "Call remote 'PUT /users/{user-id}/manager/$ref' operation".
PS> Set-EntraUserManager -ObjectId $AdeleM.Id -RefObjectId $Diego.id -Debug:$false  
DEBUG: [CmdletBeginProcessing]: - Set-MgUserManagerByRef begin processing with parameterSet 'Set'.
DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph Command Line Tools'.
...
```

**Comment by snehalkotwal** [comment]
@alexandair Thanks for raising the issue, we are looking into it.

**Comment by SteveMutungi254** [comment]
@alexandair: This issue has been fixed. Tagging you for awareness as the OP. The issue closes once the moment the PR is merged.

I will reopen the issue in case it does not meet the acceptance criteria.
