### ISSUE TITLE
Set-EntraApplicationLogo does not work as documented

### ISSUE THREAD

**Issue by benjiwolfe** [microsoftgraph/entra-powershell#886]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of `Microsoft.Graph.Entra` or `Microsoft.Graph.Entra.Beta`.
- Please search the existing issues to see if there has been a similar issue filed.

**Describe the bug**
> There are two issues with the Set-EntraApplicationLogo cmdlet that I have uncovered that occur with the v1.0 and Beta.

1. The [documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.entra/set-entraapplicationlogo?view=entra-powershell) is incorrect and the example provided doesn't work:

`Set-EntraApplicationLogo -ObjectId 'aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb' -FilePath 'D:\applogo.jpg'`

Running this results in the following error:

**Get-Content: Cannot process argument transformation on parameter 'Encoding'. 'Byte' is not a supported encoding name. For
information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter
'name')**

2. There is a hardcoded, hidden, and required variable not exposed that is required to be set in order to successfully run the cmdlet. The variable is called $logobytes.

![image](https://github.com/microsoftgraph/entra-powershell/assets/44454813/979deb21-016e-4cb1-aa27-78e580df9826)

To get this cmdlet to successfully run and upload an image onto the app the whole command ends up looking likes this:

```
$imagepath = "C:\Temp\jwt.png"
$logoBytes = [System.IO.File]::ReadAllBytes($imagePath)
Set-EntraApplicationLogo -ObjectId 'aafd364a-f4dd-4283-9e80-5768fa98aa84' -ImageByteArray $imageBytes
```

**To Reproduce**
1. Execute `Set-EntraApplicationLogo -ObjectId 'aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb' -FilePath 'D:\applogo.jpg`
2. See error above.

**Expected behavior**
I would expect to be able to run the cmdlet "as is" per the documentation by pointing it at the .jpg without having to use a byte array. 

**Debug Output**
> Run the problematic command with `-Debug` and paste the resulting debug stream below.
> ⚠ ATTENTION: Be sure to remove any sensitive information that may be in the logs.

**Module Version**
![image](https://github.com/microsoftgraph/entra-powershell/assets/44454813/ac1f7d5a-aed3-4007-b790-37d1d4401aaa)

**Environment Data**
![image](https://github.com/microsoftgraph/entra-powershell/assets/44454813/25dea6a6-5b82-4b42-b4a0-f4b609e73337)

**Screenshots**
![image](https://github.com/microsoftgraph/entra-powershell/assets/44454813/99837a64-4e93-47ba-81ab-db288a7a25ed)

![image](https://github.com/microsoftgraph/entra-powershell/assets/44454813/c0c3dbcb-23ad-40f9-9787-44897719643a)

**Additional context**
> Add any other context about the problem here.

**Comment by snehalkotwal** [comment]
@benjiwolfe Thanks for raising the issue, we are looking into it.

**Comment by v-varshamane** [comment]
Hi @benjiwolfe 

This issue has been resolved. The changes will be availed by 12th July new release.
