### ISSUE TITLE
Get-EntraUser's -Top parameter doesn't work as expected when combined with the -All parameter

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/entra-powershell#892]
`Get-EntraUser -Top $topValue -All` should return `$topValue` number of users.
At the moment, it returns all users which is wrong.

```powershell
# incorrect output
PS> Get-EntraUser -Top 5 -All | Measure-Object

Count             : 29

# compare it to Microsoft Graph PowerShell
PS> Get-MgUser -Top 5 -All | Measure-Object

Count             : 5

# Without -All
PS> Get-EntraUser -Top 5 | Measure-Object

Count             : 5
```

**Comment by v-varshamane** [comment]
@alexandair Thanks for raising the issue, We are looking into it.

**Comment by KenitoInc** [comment]
@alexandair 
I wonder if we have a legitimate usecase for having both Top and All parameters used within the same command.
Can we enforce not using them together?

**Comment by alexandair** [comment]
I agree that -Top and -All shouldn't be in the same parameter set.
But, what we are missing is the -PageSize parameter.

-Top is also unfortunate parameter name. 
-Limit is much better one.

We should have one parameter set with the -Limit and -PageSize.
And the other parameter set with the -All and -PageSize.

Microsoft Graph PowerShell SDK also has wrong implementation of the -Top, -PageSize, and -All and allows all 3 parameters in the same parameter set.

Can you guess how many users you get with `Get-MgUser -Top 7 -PageSize 5`?
