### ISSUE TITLE
Why do we have Get-EntraContext and Get-EntraCurrentSessionInfo?

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/entra-powershell#902]
Both` Get-EntraContext` and `Get-EntraCurrentSessionInfo` are wrapper functions for `Get-MgContext`.

First, why do we need both of them?
Second, they are written incorrectly:
`Get-EntraContext` doesn't support all common parameters.
`Get-EntraCurrentSessionInfo` has the `-Property` parameter that doesn't work because `Get-MgContext` doesn't support the `-Property` parameter.

**Comment by snehalkotwal** [comment]
@alexandair Thanks for raising the issue, We are looking into it.

**Comment by alexandair** [comment]
Nothing stops you of having a proper `Get-EntraContext` and then make `Get-EntraCurrentSessionInfo` an alias to it.

**Comment by SteveMutungi254** [comment]
@alexandair : That is the plan and implementation is underway.

**Comment by v-varshamane** [comment]
Hi @alexandair

This issue has been resolved. The changes are available in latest release 0.11.0-preview.
We have removed Get-EntraCurrentSessionInfo cmdlets and make Get-EntraCurrentSessionInfo alias of Get-EntraContext

Thanks

**Comment by alexandair** [comment]
> Hi @alexandair
> 
> This issue has been resolved. The changes are available in latest release 0.11.0-preview.
> We have removed Get-EntraCurrentSessionInfo cmdlets and make Get-EntraCurrentSessionInfo alias of Get-EntraContext
> 

I don't get Get-EntraCurrentSessionInfo as an alias in 0.11.0-preview.

**Comment by v-varshamane** [comment]
Hi @alexandair 

This is working after running Enable-EntraAzureADAlias cmd.
But we thought that this should not be dependency so we managed to remove this dependency.
Fix will be there in next release.

Thanks
