### ISSUE TITLE
Only first execution of Get-EntraCurrentSessionInfo doesn't produce an error

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/entra-powershell#903]
First execution of the Get-EntraCurrentSessionInfo command works as expected. After that you will get an error message:
```powershell
PS> Get-EntraCurrentSessionInfo
Add-Member: Cannot add a member with the name "ObjectId" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.
```

**Comment by snehalkotwal** [comment]
@alexandair Thanks for raising the issue, We are looking into it.

**Comment by v-varshamane** [comment]
Hi @alexandair 
This issue has been resolved. The changes will be availed by 12th July new release.
