### ISSUE TITLE
Help documentation issue - Find-EntraPermissions examples are incorrect

### ISSUE THREAD

**Issue by TomAafloen** [microsoftgraph/entra-powershell#906]
**Describe the bug**
The example commands in **Get-Help Find-EntraPermissions -Examples** does not work.

**To Reproduce**
1. Execute `Get-Help Find-EntraPermissions -Examples`
2. Copy any of the two example command (like `Find-EntraPermissions application`)
3. Run the example command

**Expected behavior**
A list of permissions, but I get this:
![Image](https://github.com/microsoftgraph/entra-powershell/assets/29425904/af060df3-18fb-48a8-af7e-276c73a4c24b)

To get the expected output I need to add **-SearchString**:
![Image](https://github.com/microsoftgraph/entra-powershell/assets/29425904/71e904ab-e2a5-4d2a-bd8f-8c18b21e338a)

**Module Version**
0.10.0

**Comment by snehalkotwal** [comment]
@TomAafloen Thanks for raising the issue we are looking into it.

**Comment by v-varshamane** [comment]
Hi @TomAafloen 

This issue has been resolved. The changes will be availed by 12th July new release.
