### ISSUE TITLE
Typo in "Get-EntraDomainFedrationSettings" ("fedration" -> "federation")

### ISSUE THREAD

**Issue by cnotin** [microsoftgraph/entra-powershell#907]
**Describe the bug**
This cmdlet has a typo in "fedration": `Get-EntraDomainFedrationSettings`

**To Reproduce**
N/A

**Expected behavior**
It should be called "federation" -> `Get-EntraDomainFederationSettings`

**Debug Output**
N/A

**Module Version**
Present in "main" branch as of today

**Comment by snehalkotwal** [comment]
@cnotin  Thanks for raising the issue we are looking into it.

**Comment by v-varshamane** [comment]
Hi @cnotin 

This issue has been resolved. The changes will be availed by 12th July new release.
Thanks for your contribution!!
