### ISSUE TITLE
Get-EntraUser makes unnecessary call with UPN value is passed to ObjectId parameter

### ISSUE THREAD

**Issue by ZachEdwards7** [microsoftgraph/entra-powershell#936]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of `Microsoft.Graph.Entra` or `Microsoft.Graph.Entra.Beta`.
- Please search the existing issues to see if there has been a similar issue filed.

**Describe the bug**
[Per Graph docs](https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#http-request), it is perfectly legal to GET a user by UPN. However, when Get-EntraUser is called with UPN value, the module makes a unnecessary call to first get the User's Id value. Then it uses the Id value in the final call to Graph /users/
This entire if statement block should be omitted -- https://github.com/microsoftgraph/entra-powershell/blob/5b5b3914f259665cad8a0357283d5b50de8b763a/module/Entra/customizations/Get-EntraUser.ps1#L45-L59

**To Reproduce**
`Get-EntraUser -ObjectId user@contoso.com`

**Expected behavior**
When UPN is provided, Get-EntraUser should make the API call using the UPN value, and not waste an API call for the sole purpose of getting the user's Id value. `Get-MgUser` and `Get-AzureADUser` both allow UPN input without making an extra API call. 

**Debug Output**
> Run the problematic command with `-Debug` and paste the resulting debug stream below.
> ⚠ ATTENTION: Be sure to remove any sensitive information that may be in the logs.

**Module Version**
> Please run `Get-Module Microsoft.Graph.Entra*` after cmdlet execution and paste the output below.
> If a module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by snehalkotwal** [comment]
@ZachEdwards7  Thanks for raising the issue, We are looking into it.
