### ISSUE TITLE
Get-EntraUser degrades gracelessly compared to Get-MGUser because of hardcoded $select

### ISSUE THREAD

**Issue by kkgthb** [microsoftgraph/entra-powershell#952]
**Describe the bug**
Right now, if you run `Get-EntraUser` without an explicit list of `-Properties` you'd like to select, the function is [hard-coded to decide for you](https://github.com/microsoftgraph/entra-powershell/blob/main/module/Entra/customizations/Get-EntraUser.ps1?plain=#L15-L25) that you must be explicitly trying to select the following property list:

```
Id,AccountEnabled,AgeGroup,OfficeLocation,AssignedLicenses,AssignedPlans,City,CompanyName,ConsentProvidedForMinor,Country,CreationType,Department,DisplayName,GivenName,OnPremisesImmutableId,JobTitle,LegalAgeGroupClassification,Mail,MailNickName,MobilePhone,OnPremisesSecurityIdentifier,OtherMails,PasswordPolicies,PasswordProfile,PostalCode,PreferredLanguage,ProvisionedPlans,OnPremisesProvisioningErrors,ProxyAddresses,RefreshTokensValidFromDateTime,ShowInAddressList,State,StreetAddress,Surname,BusinessPhones,UsageLocation,UserPrincipalName,ExternalUserState,ExternalUserStateChangeDateTime,UserType,OnPremisesLastSyncDateTime,ImAddresses,SecurityIdentifier,OnPremisesUserPrincipalName,ServiceProvisioningErrors,IsResourceAccount,OnPremisesExtensionAttributes,DeletedDateTime,OnPremisesSyncEnabled,EmployeeType,EmployeeHireDate,CreatedDateTime,EmployeeOrgData,preferredDataLocation,Identities,onPremisesSamAccountName,EmployeeId,EmployeeLeaveDateTime,AuthorizationInfo,FaxNumber,OnPremisesDistinguishedName,OnPremisesDomainName,IsLicenseReconciliationNeeded,signInSessionsValidFromDateTime,SignInActivity
```

Adding a `-Debug` switch to `Get-MgUser`, on the other hand, reveals that it simply does not include a `$select=...` at all in the HTTP request to the Graph API if you do not bother to explicitly specify which properties you would like to query.

The result is that:

1. `Get-MgUser` without an explicit `-Property` **succeeds** if `(Get-EntraContext).Scopes` includes _something_ that allows _some_ user details to be accessed through `https://graph.microsoft.com/v1.0/users/` _([Graph Explorer example here](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%2Fexample%40example.com&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com))_.
2. `Get-EntraUser` without an explicit `-Property` list **fails** if `(Get-EntraContext).Scopes.Contains('User.Read.All')` is `false`, even if the logged-in user's scope otherwise allows _some_ user details to be accessed through `https://graph.microsoft.com/v1.0/users/`, because Get-EntraUser tries to download an explicit kitchen-sink list of user properties, some of which people without `User.Read.All` scope are not allowed to view.

**To Reproduce**
1. Execute `Connect-Entra -TenantId SOME_TENANT_ID_HERE` with a user for whom the following are all true:
    1. ```powershell
        (Get-MgUser -UserId 'SOME_USER_IDENTIFIER_HERE').Count -eq 1
        ```
    1. ```powershell
        (Get-MgUser -UserId 'SOME_USER_IDENTIFIER_HERE' -Property @('Id','UserPrincipalName')).Count -eq 1
        ```
    1. ```powershell
        $my_temporary_error_output = @()
        Get-MgUser -UserId 'SOME_USER_IDENTIFIER_HERE' -Property @('Id','SignInActivity') -ErrorAction 'SilentlyContinue' -ErrorVariable 'my_temporary_error_output'
        $my_temporary_error_output.FullyQualifiedErrorId -eq 'Authentication_RequestFromUnsupportedUserRole,Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_Get'
        ```
    1. ```powershell
        (Get-EntraUser -ObjectId 'SOME_USER_IDENTIFIER_HERE' -Property @('Id','UserPrincipalName')).Count -eq 1
        ```
2. Execute and validate that the following is `true` _(errors out as `Authentication_RequestFromUnsupportedUserRole`)_:
    ```powershell
    $my_temporary_error_output = @()
    Get-EntraUser -ObjectId 'SOME_USER_IDENTIFIER_HERE' -ErrorAction 'SilentlyContinue' -ErrorVariable 'my_temporary_error_output'
    $my_temporary_error_output.ErrorRecord.ErrorDetails.Message -Match 'Authentication_RequestFromUnsupportedUserRole'
    ```

**Expected behavior**

1. `(Get-EntraUser -ObjectId 'SOME_USER_IDENTIFIER_HERE').Count -eq 1` should be `true` and simply only return the data that a `$select`-less Graph API call would return, not get forced into an `Authentication_RequestFromUnsupportedUserRole` by deciding _for_ the person using `Get-EntraUser` exactly which properties they meant to include.
    * _(It is fine to try the full property list, but at least fall back to trying a `$select`-less version if it errors out this way, so that it behaves equivalently to `Get-MgUser`.)_

**Debug Output**

  ```powershell
  Get-EntraUser -ObjectId 'an_email@example.com' -Debug
  
  DEBUG: GET /v1.0/users/an_email@example.com HTTP/1.1
  HTTP: graph.microsoft.com
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19045; en-US) PowerShell/7.4.3 Invoke-MgGraphRequest
   
  DEBUG: GET https://graph.microsoft.com/v1.0/users/an_email@example.com
  HTTP/2.0 200 OK
  Cache-Control: no-cache
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=31536000
  request-id: OBFUSCATED
  client-request-id: OBFUSCATED
  x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"OBFUSCATED"...}}
  x-ms-resource-unit: 1
  odata-version: 4.0
  Date: Wed, 24 Jul 2024 18:07:53 GMT
  Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; IEEE754Compatible=false; charset=utf-8
  Content-Encoding: gzip
   
  {"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users/$entity","businessPhones":["+1 555-555-5555"],"displayName":"A Name","givenName":"TheFirstName","jobTitle":"A Job Title","mail":"an_email@example.com","mobilePhone":"+1 555-555-5555","officeLocation":"Sunny Street","preferredLanguage":null,"surname":"TheLastName","userPrincipalName":"an_email@example.com","id":"the_user_id"}
  DEBUG: ============================ TRANSFORMATIONS ============================
  DEBUG: Uri : https://graph.microsoft.com/v1.0/users/the_user_id?$select=Id,AccountEnabled,AgeGroup,OfficeLocation,AssignedLicenses,AssignedPlans,City,CompanyName,ConsentProvidedForMinor,Country,CreationType,Department,DisplayName,GivenName,OnPremisesImmutableId,JobTitle,LegalAgeGroupClassification,Mail,MailNickName,MobilePhone,OnPremisesSecurityIdentifier,OtherMails,PasswordPolicies,PasswordProfile,PostalCode,PreferredLanguage,ProvisionedPlans,OnPremisesProvisioningErrors,ProxyAddresses,RefreshTokensValidFromDateTime,ShowInAddressList,State,StreetAddress,Surname,BusinessPhones,UsageLocation,UserPrincipalName,ExternalUserState,ExternalUserStateChangeDateTime,UserType,OnPremisesLastSyncDateTime,ImAddresses,SecurityIdentifier,OnPremisesUserPrincipalName,ServiceProvisioningErrors,IsResourceAccount,OnPremisesExtensionAttributes,DeletedDateTime,OnPremisesSyncEnabled,EmployeeType,EmployeeHireDate,CreatedDateTime,EmployeeOrgData,preferredDataLocation,Identities,onPremisesSamAccountName,EmployeeId,EmployeeLeaveDateTime,AuthorizationInfo,FaxNumber,OnPremisesDistinguishedName,OnPremisesDomainName,IsLicenseReconciliationNeeded,signInSessionsValidFromDateTime,SignInActivity
  DEBUG: Method : GET
  DEBUG: =========================================================================
   
  DEBUG: GET /v1.0/users/the_user_id?$select=Id,AccountEnabled,AgeGroup,OfficeLocation,AssignedLicenses,AssignedPlans,City,CompanyName,ConsentProvidedForMinor,Country,CreationType,Department,DisplayName,GivenName,OnPremisesImmutableId,JobTitle,LegalAgeGroupClassification,Mail,MailNickName,MobilePhone,OnPremisesSecurityIdentifier,OtherMails,PasswordPolicies,PasswordProfile,PostalCode,PreferredLanguage,ProvisionedPlans,OnPremisesProvisioningErrors,ProxyAddresses,RefreshTokensValidFromDateTime,ShowInAddressList,State,StreetAddress,Surname,BusinessPhones,UsageLocation,UserPrincipalName,ExternalUserState,ExternalUserStateChangeDateTime,UserType,OnPremisesLastSyncDateTime,ImAddresses,SecurityIdentifier,OnPremisesUserPrincipalName,ServiceProvisioningErrors,IsResourceAccount,OnPremisesExtensionAttributes,DeletedDateTime,OnPremisesSyncEnabled,EmployeeType,EmployeeHireDate,CreatedDateTime,EmployeeOrgData,preferredDataLocation,Identities,onPremisesSamAccountName,EmployeeId,EmployeeLeaveDateTime,AuthorizationInfo,FaxNumber,OnPremisesDistinguishedName,OnPremisesDomainName,IsLicenseReconciliationNeeded,signInSessionsValidFromDateTime,SignInActivity HTTP/1.1
  HTTP: graph.microsoft.com
  User-Agent: PowerShell/7.4.3 EntraPowershell/0.11.0 Get-EntraUser
   
   
  DEBUG: GET https://graph.microsoft.com/v1.0/users/the_user_id?$select=Id,AccountEnabled,AgeGroup,OfficeLocation,AssignedLicenses,AssignedPlans,City,CompanyName,ConsentProvidedForMinor,Country,CreationType,Department,DisplayName,GivenName,OnPremisesImmutableId,JobTitle,LegalAgeGroupClassification,Mail,MailNickName,MobilePhone,OnPremisesSecurityIdentifier,OtherMails,PasswordPolicies,PasswordProfile,PostalCode,PreferredLanguage,ProvisionedPlans,OnPremisesProvisioningErrors,ProxyAddresses,RefreshTokensValidFromDateTime,ShowInAddressList,State,StreetAddress,Surname,BusinessPhones,UsageLocation,UserPrincipalName,ExternalUserState,ExternalUserStateChangeDateTime,UserType,OnPremisesLastSyncDateTime,ImAddresses,SecurityIdentifier,OnPremisesUserPrincipalName,ServiceProvisioningErrors,IsResourceAccount,OnPremisesExtensionAttributes,DeletedDateTime,OnPremisesSyncEnabled,EmployeeType,EmployeeHireDate,CreatedDateTime,EmployeeOrgData,preferredDataLocation,Identities,onPremisesSamAccountName,EmployeeId,EmployeeLeaveDateTime,AuthorizationInfo,FaxNumber,OnPremisesDistinguishedName,OnPremisesDomainName,IsLicenseReconciliationNeeded,signInSessionsValidFromDateTime,SignInActivity
  HTTP/2.0 403 Forbidden
  Cache-Control: no-cache
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=31536000
  request-id: OBFUSCATED
  client-request-id: OBFUSCATED
  x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"OBFUSCATED"...}}
  x-ms-resource-unit: 1
  Date: Wed, 24 Jul 2024 18:07:54 GMT
  Content-Type: application/json
  Content-Encoding: gzip
   
  {"error":{"code":"Authentication_RequestFromUnsupportedUserRole","message":"User is not in the allowed roles","innerError":{"date":"2024-07-24T18:07:54","request-id":"OBFUSCATED","client-request-id":"OBFUSCATED"}}}
  Invoke-MgGraphRequest: GET
  https://graph.microsoft.com/v1.0/users/the_user_id?$select=Id,AccountEnabled,AgeGroup,OfficeLocation,AssignedLicenses,AssignedPlans,City,CompanyName,ConsentProvidedForMinor,Country,CreationType,Department,Display
  Name,GivenName,OnPremisesImmutableId,JobTitle,LegalAgeGroupClassification,Mail,MailNickName,MobilePhone,OnPremisesSecurityIdentifier,OtherMails,PasswordPolicies,PasswordProfile,PostalCode,PreferredLanguage,ProvisionedPlans,OnPremisesProv
  isioningErrors,ProxyAddresses,RefreshTokensValidFromDateTime,ShowInAddressList,State,StreetAddress,Surname,BusinessPhones,UsageLocation,UserPrincipalName,ExternalUserState,ExternalUserStateChangeDateTime,UserType,OnPremisesLastSyncDateTi
  me,ImAddresses,SecurityIdentifier,OnPremisesUserPrincipalName,ServiceProvisioningErrors,IsResourceAccount,OnPremisesExtensionAttributes,DeletedDateTime,OnPremisesSyncEnabled,EmployeeType,EmployeeHireDate,CreatedDateTime,EmployeeOrgData,p
  referredDataLocation,Identities,onPremisesSamAccountName,EmployeeId,EmployeeLeaveDateTime,AuthorizationInfo,FaxNumber,OnPremisesDistinguishedName,OnPremisesDomainName,IsLicenseReconciliationNeeded,signInSessionsValidFromDateTime,SignInAc
  tivity HTTP/2.0 403 Forbidden Cache-Control: no-cache Vary: Accept-Encoding Strict-Transport-Security: max-age=31536000 request-id: OBFUSCATED client-request-id: OBFUSCATED
  x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"OBFUSCATED"...}} x-ms-resource-unit: 1 Date: Wed, 24 Jul 2024 18:07:54 GMT Content-Type: application/json
  Content-Encoding: gzip  {"error":{"code":"Authentication_RequestFromUnsupportedUserRole","message":"User is not in the allowed
  roles","innerError":{"date":"2024-07-24T18:07:54","request-id":"OBFUSCATED","client-request-id":"OBFUSCATED"}}}
  ```

**Module Version**
```
ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     0.11.0     preview    Microsoft.Graph.Entra
```

`Microsoft.Graph.Entra` 0.11.0 preview

**Environment Data**

```
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**
I suppose this is probably in that gray zone between a bug and a feature; sorry if I chose the wrong template.  :)

**Comment by snehalkotwal** [comment]
@kkgthb Thanks for raising the bug, we are looking into it.

**Comment by adamedx** [comment]
Can we clarify the concern here -- I don't think it is a design goal to emulate `Get-MgUser`. In fact, the goal was to behave like `Get-AzureAdUser`. If this command behaves like the latter, this seems by design. If there is a workaround like explicitly specifying `Properties` then it seems like there is no issue here; we should though clarify the design philosophy in the repository and / or documentation.

**Comment by alexandair** [comment]
In short term, Entra PowerShell goal should be an easier migration from the AzureAD module to the Microsoft Graph-based commands, however, it shouldn't blindly follow AzureAD's design decisions.

There must be a reason why Microsoft Graph PowerShell SDK commands return just a subset of Entra objects' properties by default, right?

The problem with Graph PowerShell is that specifying the `-Select/-Property` parameter will return only the specified properties and neglect the default properties. That's absolutely unexpected behavior for PowerShell users. Azure PowerShell team fixed that introducing the `-AppendSelected` parameter.

For example:
`Get-AzADUser` returns default properties

`Get-AzADUser -Select` returns ONLY selected properties

`Get-AzADUser -Select -AppendSelected` returns default+selected properties

Why couldn't this be implemented in Entra PowerShell and give users a user-friendly control on returned properties?

Most of the users of the `Get-EntraUser` command wouldn't even notice the difference between `Get-MgUser` and `Get-EntraUser`, if `SignInActivity` property (returned by default with `Get-EntraUser`) didn't require an additional permission, `AuditLog.Read.All`.

That means that Microsoft is forcing users of `Get-EntraUser` to have `User.Read.All` and `AuditLog.Read.All` permissions even when users aren't interested in the `SignInActivity` property. How is that going with the least privilege model?

**Comment by SteveMutungi254** [comment]
@alexandair : The `-AppendSelected` feature is part of our priority list in a quarter or two.

**Comment by adamedx** [comment]
> In short term, Entra PowerShell goal should be an easier migration from the AzureAD module to the Microsoft Graph-based commands, however, it shouldn't blindly follow AzureAD's design decisions.
> 
> There must be a reason why Microsoft Graph PowerShell SDK commands return just a subset of Entra objects' properties by default, right?
> 
> The problem with Graph PowerShell is that specifying the `-Select/-Property` parameter will return only the specified properties and neglect the default properties. That's absolutely unexpected behavior for PowerShell users. Azure PowerShell team fixed that introducing the `-AppendSelected` parameter.
> 
> For example: `Get-AzADUser` returns default properties
> 
> `Get-AzADUser -Select` returns ONLY selected properties
> 
> `Get-AzADUser -Select -AppendSelected` returns default+selected properties
> 
> Why couldn't this be implemented in Entra PowerShell and give users a user-friendly control on returned properties?
> 
> Most of the users of the `Get-EntraUser` command wouldn't even notice the difference between `Get-MgUser` and `Get-EntraUser`, if `SignInActivity` property (returned by default with `Get-EntraUser`) didn't require an additional permission, `AuditLog.Read.All`.
> 
> That means that Microsoft is forcing users of `Get-EntraUser` to have `User.Read.All` and `AuditLog.Read.All` permissions even when users aren't interested in the `SignInActivity` property. How is that going with the least privilege model?

I think `-AppendSelected` is a great idea -- looking forward to it! And agreed that optimizing for `AzureAD` expectations is probably the most expedient way to go.

The last observation about permissions is not strictly true -- `Get-EntraUser` does not fail if you don't have those permissions -- those properties simply don't get returned. This is in turn just a reflection of how the underlying MS Graph API functions (https://graph.microsoft.com/v1.0/users/<userid>).

As far as "why does `Get-MgUser` act the way it does with fewer properties, as far as I can tell there is actually not a reason for this other than "That's how the MS Graph API works," i.e. `Get-MgUser` == 'https://graph.microsoft.com/v1.0/users/<blah>`. So if you try that URI in Graph Explorer for instance you *should* see the same properties that are getting returned by default with `Get-MgUser`. (I am saying this without looking at the code for `Get-MgUser`, perhaps somehow it does indeed limit the properties, but it is well-known that `v1.0` only returns "default" properties).

One thing to try with `Get-MgUser` -- does `Get-MgBetaUser` return more properties? If so, that's not a surprise either because the underlying `beta` API version of MS Graph returns *all* properties by default.

So the claim I'm making here is that `Get-MgUser` just happens to do whatever the underlying API does. The behavior of MS Graph API was optimized for generic app scenarios and not specifically PowerShell use cases for instance (certainly not AzureAD PS parity). So to me `Get-MgUser` default behavior is not a benchmark for that of other graph-based PowerShell experiences.

**Comment by adamedx** [comment]
A little more about default properties in MS Graph API on which my `Get-MgUser` theory is based: https://stackoverflow.com/questions/48229949/get-all-user-properties-from-microsoft-graph.

Maybe just look at your request URI when issuing `Get-MgUser` (via `-debug`?) to see if it's limiting the result set itself or going with default MS Graph API behavior.

**Comment by kkgthb** [comment]
> A little more about default properties in MS Graph API on which my `Get-MgUser` theory is based: https://stackoverflow.com/questions/48229949/get-all-user-properties-from-microsoft-graph.
> 
> Maybe just look at your request URI when issuing `Get-MgUser` (via `-debug`?) to see if it's limiting the result set itself or going with default MS Graph API behavior.

I forgot to include `-debug` information from `Get-MgUser`.

1. `Get-MgUser -debug` reveals that it does, indeed, merely call `https://graph.microsoft.com/v1.0/users/the_user_id`.
2. Whereas `Get-EntraUser -debug` calls `https://graph.microsoft.com/v1.0/users/the_user_id?$select=long_list_of_hard_coded_properties`.

This is why I suggested that:

* Even if for some reason Microsoft is absolutely positively convinced that people want Microsoft to offer a mechanism by which they make it clear which properties are "all the properties" (that is, be the ones to maintain a trustworthy, official copy of the string "`Id,AccountEnabled,...,SignInActivity`" somewhere handy)...
* Microsoft should still at least make `Get-EntraUser` _try_ behaving like `Get-MgUser` if the hardcoding returns an `Authentication_RequestFromUnsupportedUserRole` before completely erroring out.
    * `Get-EntraUser` should gracefully handle exceptions arising from `Get-AzADUser`'s [slightly awkwardly paternalistic "if you don't specify a `$select`, I'm going to pick one for you" behavior](https://github.com/microsoftgraph/entra-powershell/blob/main/module/Entra/customizations/Get-EntraUser.ps1?plain=#L15-L25)...
    * ...and try one more time with `Get-MgUser`'s "hey, let's just not presume we know what `$select` the user meant if they didn't specify one and leave it off the underlying Graph call altogether" approach.

Or, if that would break a contract that Microsoft can't go back on their word about saying something like:
* `Get-EntraUser` will, forever and for all time, never behave more maturely than `Get-AzADUser` did, so that no one ever ever ever has to refactor code... _(ahem:)_
    > In short term, Entra PowerShell goal should be an easier migration from the AzureAD module to the Microsoft Graph-based commands, however, it shouldn't blindly follow AzureAD's design decisions.
* ... Then Microsoft should at least add something like a **concise** `Get-EntraUser -NoSelect` or `Get-EntraUser -MgStyle` flag that lets people who currently have no problems using `Get-MgUser` enjoy `Get-EntraUser` without having to type 50-bazillion things into `-Properties` by hand to get around `Get-EntraUser`'s insistence on telling you "you'll take these `$select`s and you'll like it!" default behavior.
    * Because clearly not everyone _does_ "like it."
        > The current set is really bad!
        > 
        > Please don't ask hard coded for everything but at least check if the user has permissions to read a property

Changing topics slightly to clear up a detail:

> Most of the users of the `Get-EntraUser` command wouldn't even notice the difference between `Get-MgUser` and `Get-EntraUser`, if `SignInActivity` property (returned by default with `Get-EntraUser`) didn't require an additional permission, `AuditLog.Read.All`.
> 
> That means that Microsoft is forcing users of `Get-EntraUser` to have `User.Read.All` and `AuditLog.Read.All` permissions even when users aren't interested in the `SignInActivity` property. How is that going with the least privilege model?

For what it's worth, `Get-MgUser` doesn't **only** work without `AuditLog.Read.All`.

`Get-MgUser` and the underlying Graph API also **work gracefully** even without `User.Read.All`.

As documented in the original bug report, when I run `Connect-Entra` without a `-Scopes` flag at all, my `(Get-EntraContext).Scopes` includes _neither_ `User.Read.All` _nor_ `AuditLog.Read.All`.

That is, `(Get-EntraContext).Scopes.Contains('User.Read.All')` is false for me.

I'm not sure which of the 19 scopes I end up with is responsible for `https://graph.microsoft.com/v1.0/users/the_user_id` _(URL-parameterless; no `$select` at all)_ and thereby `Get-MgUser` **working** for me, but clearly [the Graph API itself](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%2Fexample%40example.com&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com) doesn't require me to even have `User.Read.All`.
