### ISSUE TITLE
No params are marked as required in New-EntraConditionalAccessPolicy

### ISSUE THREAD

**Issue by KenitoInc** [microsoftgraph/entra-powershell#983]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of `Microsoft.Graph.Entra` or `Microsoft.Graph.Entra.Beta`.
- Please search the existing issues to see if there has been a similar issue filed.

**Describe the bug**
> A clear and concise description of what the bug is.

No params are marked as required in New-EntraConditionalAccessPolicy despite `DisplayName`, `Conditions (Users and Applications)` and `Controls` being required params.
<img width="598" alt="image" src="https://github.com/user-attachments/assets/1d766429-2fb3-4bf0-8bf7-4c9557d860e6">

**To Reproduce**
1. Execute `New-EntraConditionalAccessPolicy ` with no params.
2. See error on PowerShell output.
3. Execute `help New-EntraConditionalAccessPolicy`.
4. See the parameters sections.

**Expected behavior**
> A clear and concise description of what you expected to happen.

Executing `New-EntraConditionalAccessPolicy ` with no params should prompt entry for the required params

**Debug Output**
> Run the problematic command with `-Debug` and paste the resulting debug stream below.
> ⚠ ATTENTION: Be sure to remove any sensitive information that may be in the logs.

**Module Version**
v0.12.0

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by v-akarke** [comment]
Hi @KenitoInc 
The parameter definition for this cmdlet is handled by the framework, which has inherited it from the original AzureAD cmdlet. In the original cmdlet, no parameters were marked as mandatory, so the New-AzureADMSConditionalAccessPolicy (AzureAD) cmdlet doesn't prompt for required parameters either. Similarly, in the MgGraph cmdlet, no parameters are designated as mandatory.
![image](https://github.com/user-attachments/assets/f8f098ce-0dd7-482d-a731-320a74ca880d)

If we want to enforce required parameters, we would need to update the parameter definition. This would require customizing the parameter definition accordingly.

CC : @v-varshamane
