### ISSUE TITLE
Migrate ESRPCodeSigning to v5

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/entra-powershell#991]
example https://github.com/microsoft/kiota-dotnet/pull/320

**Comment by KenitoInc** [comment]
WIP
We are migrating the pipeline from microsoftgraph to msazure. We will configure v5 in the new pipeline

**Comment by baywet** [comment]
Thanks for the update. Once the migration is completed, can you please delete or archive the pipeline in microsoftgraph? This way it won't appear as infringing anymore.

**Comment by SteveMutungi254** [comment]
Great call out @baywet. We will do that. cc: @KenitoInc.

**Comment by Onokaev** [comment]
Hey @SteveMutungi254. Gentle ping on this upgrade. We have a security item that requires deleting the current service connection you are using for ESRP Code Signing

**Comment by SteveMutungi254** [comment]
@Onokaev, @KenitoInc will do this.

**Comment by baywet** [comment]
Note: the migration work has started here
https://github.com/microsoftgraph/entra-powershell/blob/6716b83f169e627047f8c80b54a0d5f5e880c02f/.azure-pipelines/common-templates/esrp/codesign-nuget-migrate.yml#L16
I believe the older file will eventually be replaced/removed and we can proceed with the deletion of the old connection.
https://github.com/microsoftgraph/entra-powershell/blob/6716b83f169e627047f8c80b54a0d5f5e880c02f/.azure-pipelines/common-templates/esrp/codesign-nuget.yml#L17

**Comment by KenitoInc** [comment]
Resolved by #1067
